import argparse
import time
import pandas as pd
from influxdb_client import InfluxDBClient
from datetime import datetime

# InfluxDB connection parameters
URL = "http://192.168.3.14:8086"
TOKEN = "pf-OGC6AQFmKy64gOzRM12DZrCuavnWeMgRZ2kDMOk8LYK22evDJnoyKGcmY49EgT8HnMDE9GPQeg30vXeHsRQ=="
ORG = "belimo"
BUCKET = "actuator-data"

def main():
    parser = argparse.ArgumentParser(description="Continuously stream actuator data to a CSV file.")
    parser.add_argument(
        "event_name",
        type=str,
        help="Description of the recording event (used as the filename)"
    )
    args = parser.parse_args()

    # Create safe filename
    safe_event_name = "".join([c if c.isalnum() else "_" for c in args.event_name])
    filename = f"{safe_event_name}.csv"

    print(f"Starting continuous recording for event: '{args.event_name}'")
    print(f"Streaming data directly to {filename}...")
    print("Press CTRL-C to stop recording...\n")

    # Connect to InfluxDB
    client = InfluxDBClient(url=URL, token=TOKEN, org=ORG, verify_ssl=False)
    query_api = client.query_api()

    # We will track the latest timestamp generated BY THE PI to filter duplicates.
    # We initialize it to None so the first fetch grabs the last few seconds of data.
    last_seen_time = None
    headers_written = False
    total_rows = 0

    try:
        while True:
            # Use relative time (-5s). This is evaluated by the Raspberry Pi using
            # its own internal clock, completely bypassing your laptop's clock skew!
            query = f"""
                from(bucket:"{BUCKET}")
                |> range(start: -5s)
                |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
                |> drop(columns: ["_start", "_stop"])
            """

            try:
                # Fetch data
                df = query_api.query_data_frame(query)

                # Handle multiple tables if InfluxDB splits the response (e.g. commands vs measurements)
                if isinstance(df, list):
                    if len(df) > 0:
                        df = pd.concat(df, ignore_index=True)
                    else:
                        df = pd.DataFrame()

                if not df.empty and '_time' in df.columns:
                    # Sort chronologically
                    df = df.sort_values(by='_time')

                    # Filter out records we've already appended
                    if last_seen_time is not None:
                        df = df[df['_time'] > last_seen_time]

                    if not df.empty:
                        # Update our cursor to the newest DB timestamp in this batch
                        last_seen_time = df['_time'].max()

                        # Clean up internal influx columns before saving
                        df.drop(columns=['result', 'table'], errors='ignore', inplace=True)

                        # Append to CSV
                        mode = 'a' if headers_written else 'w'
                        df.to_csv(filename, mode=mode, header=not headers_written, index=False)

                        headers_written = True
                        new_rows = len(df)
                        total_rows += new_rows

                        # Print status using the LAPTOP's local clock just for the terminal UI
                        current_clock = datetime.now().strftime('%H:%M:%S')
                        print(f"[{current_clock}] Appended {new_rows} new rows... (Total: {total_rows})")

            except Exception as e:
                print(f"Error fetching chunk: {e}")

            # Sleep briefly. 1 second is safe because we are querying a 5-second rolling window.
            time.sleep(1.0)

    except KeyboardInterrupt:
        print("\nCTRL-C detected. Stopping stream...")
    finally:
        client.close()
        print(f"Finished. A total of {total_rows} rows were saved to {filename}.")

if __name__ == "__main__":
    main()
